<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1**

| **Term**   | **Brief Description**                                                                                         |
|:-----------|:--------------------------------------------------------------------------------------------------------------|
| Subsetting | Subsetting is the select variables in  a list of array.                                                       |
| Indexing   | Indexing is the selection of 1 variable in the list or array.                                                 |
| Slicing    | Slicing is the selection of a specified range of variables in a list or array.                                |
| Masking    | Masking is to only show the desired variables according to the specific conditions stated in  an array only.  |

**Exercise 2**

In [19]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

digit_array = np_array_2d[: , 0].astype('int')  #digit_array stores 1 to 8, 10, 9
odd_letters = np_array_2d[(digit_array)%2 == 1 , 1]  #(digit_array)%2 == 1 gives the array with True and False 
print(odd_letters)

['A' 'C' 'E' 'G' 'I']


**Exercise 3**

In [1]:
import numpy as np

np_array_2d = np.array([[66, 50, 57, -1, -1],
                        [92, -1, 88, -1, -1],
                        [75, -1, -1, 76, -1],
                        [-1, 51, 87, -1, -1],
                        [71, -1, 67, -1, 69]])

for i in range(len(np_array_2d)):
    for j in range(len(np_array_2d)):
        if np_array_2d[i , j] < 50:
            np_array_2d[i , j] = -1
        elif  np_array_2d[i , j] > 50:
            np_array_2d[i , j] = 1
        else:
            np_array_2d[i , j] = 0
        
print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
